### ISSUE TITLE
When running train.py, I meet this error

### ISSUE THREAD

**Issue by sadsearth** [bailvwangzi/repulsion_loss_ssd#12]
Loading the dataset...
Training SSD on: VOC0712
Using the specified args:
Namespace(basenet='vgg16_reducedfc.pth', batch_size=32, cuda=True, dataset='VOC', dataset_root='C:\\Users\\Admin\\data/VOCdevkit/', gamma=0.1, lr=0.001, momentum=0.9, num_workers=4, resume=None, save_folder='weights/', start_iter=0, visdom=False, weight_decay=0.0005)
train.py:181: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  targets = [Variable(ann.cuda(), volatile=True) for ann in targets]
C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "train.py", line 269, in <module>
    train()
  File "train.py", line 190, in train
    loss_l, loss_l_repul, loss_c = criterion(out, targets)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\wang\repulsion_loss_ssd\layers\modules\multibox_loss.py", line 101, in forward
    loss_l_repul = repul_loss(loc_p, loc_g, priors)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\wang\repulsion_loss_ssd\layers\modules\repulsion_loss.py", line 26, in forward
    decoded_boxes = decode_new(loc_data, Variable(prior_data.data, requires_grad=False), self.variance)
  File "D:\wang\repulsion_loss_ssd\layers\box_utils.py", line 212, in decode_new
    priors[:, :2] + loc[:, :2] * variances[0] * priors[:, 2:],
RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 2

**Comment by sadsearth** [comment]
Anyone can help me?

**Comment by TWangQing** [comment]
您好，我遇到了相同的问题，请问您解决了吗
